### ISSUE TITLE
graph vertical divider at 2000 seconds?

### ISSUE THREAD

**Issue by boolship** [artiomchi/Dual-Battery-Widget#2]
Can it be reset in increments to closer follow the wall clock?

**Comment by artiomchi** [comment]
Could you explain the "closer follow the wall clock" please? :)
I'm planning to try improve the vertical divider, but haven't decided on how to best use it yet... This will be changed soon

**Comment by boolship** [comment]
What I mean by wall clock: it would be better if based on days, hours, half-hours, minutes instead of base-10 like 2000 seconds. I realise this may not be possible because the graph scales with pinch gestures and might require base-10 vertical dividers.

**Comment by artiomchi** [comment]
I Guess it took me some time, but I've managed to get a fix for this issue. The graph will now draw the grid lines in a more "natural" matter.
The fix is now released in the Android Market
