### ISSUE TITLE
Not available from playstore anymore

### ISSUE THREAD

**Issue by vpelletier** [artiomchi/Dual-Battery-Widget#5]
Having dusted off and reinstalled my old TF700T, I wanted to install this widget (which I've been using very happily for years on all my android devices), and discovered that it is not available from google playstore anymore.

Which then led me to discover this is an open-source project (yeah, I did not read the "About" tab very seriously over all these years...). Maybe could you consider submitting it to the F-Droid appstore, if not also to the google playstore ?

**Comment by vpelletier** [comment]
.gitmodules contains reference to missing repositories. I could find what should be their upstreams versions, but pinned commits are missing:
```diff
diff --git a/.gitmodules b/.gitmodules
index 2950472..d770bf1 100644
--- a/.gitmodules
+++ b/.gitmodules
@@ -1,9 +1,9 @@
 [submodule "lib/ActionBarSherlock"]
        path = lib/ActionBarSherlock
-       url = git://github.com/artiomchi/ActionBarSherlock.git
+       url = https://github.com/JakeWharton/ActionBarSherlock.git
 [submodule "lib/AndroidBilling"]
        path = lib/AndroidBilling
-       url = git://github.com/artiomchi/AndroidBillingLibrary.git
+       url = https://github.com/robotmedia/AndroidBillingLibrary.git
 [submodule "lib/ViewPagerIndicator"]
        path = lib/ViewPagerIndicator
-       url = git://github.com/artiomchi/Android-ViewPagerIndicator.git
+       url = https://github.com/JakeWharton/Android-ViewPagerIndicator.git
diff --git a/lib/ActionBarSherlock b/lib/ActionBarSherlock
index 8a0b10d..2c71339 160000
--- a/lib/ActionBarSherlock
+++ b/lib/ActionBarSherlock
@@ -1 +1 @@
-Subproject commit 8a0b10de700d691c8751953dcf648431b245cbd1
+Subproject commit 2c71339e756bcc0b1424c4525680549ba3a2dc97
diff --git a/lib/AndroidBilling b/lib/AndroidBilling
index 4a4fc18..fc637bb 160000
--- a/lib/AndroidBilling
+++ b/lib/AndroidBilling
@@ -1 +1 @@
-Subproject commit 4a4fc181b564aef6f4c9f4a720600cd604b7b655
+Subproject commit fc637bb2ed9d0c864e1b918f9b604fb140104f6d
diff --git a/lib/ViewPagerIndicator b/lib/ViewPagerIndicator
index a4082ff..8cd549f 160000
--- a/lib/ViewPagerIndicator
+++ b/lib/ViewPagerIndicator
@@ -1 +1 @@
-Subproject commit a4082ff7a4aea4a8363d9a715c4ed97ec491318c
+Subproject commit 8cd549f23f3d20ff920e19a2345c54983f65e26b
```

**Comment by artiomchi** [comment]
Hey Vincent,

Oh man, thanks for still being interested in the app. I haven't done any development on it for a very long time, and it's WAY out of date. Even building is a bit of a challenge, as you saw yourself. 

I just took a look at F-droid, and it looks like to submit apps to them they have to build successfully, so that's a bit of a moot point too.

But not all is lost! You can always download and side-load an APK to install it locally. I've just downloaded the latest release build, and pushed it to it's release page here: https://github.com/artiomchi/Dual-Battery-Widget/releases/tag/v1.1.8%2F30

Hopefully it'll still work - it's been built for a much older version of Android SDK :)

Please let me know if you managed to install it and if not - I'll see how much work would it take to update it to a recent SDK and tooling

**Comment by vpelletier** [comment]
> Oh man, thanks for still being interested in the app.

At least I have never found a replacement which:
- doesn't add notifications/status icons
- has readable, non intrusive (ie, not flat green/orange/red rectangles) and resizeable widget (and not add 10 different versions of the same fixed-size widget)
- logs battery data without having to decide how long/how often/...
- ...and logs battery data to plot it on the phone, not just to save to CSV that I would have to pull elsewhere and plot separately to remind myself when I did the last few charges and whether it has really become more often than before

You found a sweet spot with this app.

>  I've just downloaded the latest release build, and pushed it to it's release page

Thanks a lot.

> Please let me know if you managed to install it and if not - I'll see how much work would it take to update it to a recent SDK and tooling

I just side-loaded it on my TF700T, where sadly it does not detect the keyboard/dock battery but this is certainly due to [the custom firmware](https://downloads.timduru.org/android/tf700t/K.A.T/KatKiss/7.x/dev/) I put on it to have something better than android 4. This is unfortunate, but I don't think this is for you to fix. (ping @timduru :) )

Also on a YT3-X90X (an x86, BTW), with stock android 6.

And finally, on my latest acquisition, a Nebula II with Android TV 9. There is no widget support, it hides non-TV apps in a deep submenu so I'm not sure I will use it much (and likely forget that it is here), but at least it succeeded installing and running.

So far, it all works from a "will it install and at least minimally run" point of view. No data logged yet, I'll try to keep an eye on all and report here.

**Comment by vpelletier** [comment]
One day later:
- TF700T works as expected (modulo only one battery being visible, but again I guess this is the custom firmware not being custom enough)
- YT3-X90X works as expected
- the more exotic Nebula II does not work: of the whole GUI, only the graph page is available with its 3 ranges, without the battery details, and the plotted value is stuck flat at about 42 (placeholder value maybe ?). But anyway, any non-TV app is not very usable there, so it does not make much of a difference. BTW, this is the only device where I had the "this app was built for an older version of android, it may not work as expected" warning on install.

So I believe this is all working as good as I could hope. There is no need to rework the project to a newer SDK.
